### ISSUE TITLE
SDK 23并不能编译

### ISSUE THREAD

**Issue by ChanJLee** [rantianhua/AssembleEssay#3]
` @Override
    public void onLayoutCompleted(RecyclerView.State state) {
        super.onLayoutCompleted(state);
        DebugUtil.debugFormat("FlowDragLayoutManager onLayoutComplete");
    }
`
比如这样的方法找不到

**Comment by rantianhua** [comment]
收到，SDK 里面 RecyclerView 的 API 有区别，明天处理一下。

**Comment by rantianhua** [comment]
你把你的 build.gradle 文件贴上来看一下吧，我试了 23 的 SDK 编译是没有问题的。

**Comment by rantianhua** [comment]
由于我没有复现这个问题，（不知道是不是你配置gradle的问题）而且这句代码本身没有什么用，现在代码里面已经删除，所以先close这个issue。
